AUDIO_ORDER_COLLECTION_NAME = 'audio_order'
AUDIO_ORDER_ID_ENTITY_NAME = 'id'
AUDIO_ORDER_USER_ID_ENTITY_NAME = 'userId'
AUDIO_ORDER_TITLE_ENTITY_NAME = 'title'
AUDIO_ORDER_TEXT_ENTITY_NAME = 'text'
AUDIO_ORDER_START_PAGE_ENTITY_NAME = 'startPage'
AUDIO_ORDER_END_PAGE_ENTITY_NAME = 'endPage'
AUDIO_ORDER_CLONED_ENTITY_NAME = 'cloned'
AUDIO_ORDER_AUDIO_LINK_ENTITY_NAME = 'audioLink'
AUDIO_ORDER_CHARACTERS_NAMES_ENTITY_NAME = 'charactersNames'
AUDIO_ORDER_AUDIO_SCRIPTS_ENTITY_NAME = 'scripts'


BOOK_TITLE_MIN_LENGTH = 1
BOOK_TITLE_MAX_LENGTH = 256
