AUDIO_ORDER_COLLECTION_NAME = 'audio_order'
AUDIO_ORDER_ID_ENTITY_NAME = 'ID'
AUDIO_ORDER_USER_ID_ENTITY_NAME = 'UserId'
AUDIO_ORDER_TITLE_ENTITY_NAME = 'Title'
AUDIO_ORDER_TEXT_ENTITY_NAME = 'Text'
AUDIO_ORDER_START_PAGE_ENTITY_NAME = 'StartPage'
AUDIO_ORDER_END_PAGE_ENTITY_NAME = 'EndPage'
AUDIO_ORDER_CLONED_ENTITY_NAME = 'Cloned'
AUDIO_ORDER_AUDIO_LINK_ENTITY_NAME = 'AudioLink'
AUDIO_ORDER_CHARACTERS_NAMES_ENTITY_NAME = 'CharactersNames'
AUDIO_ORDER_AUDIO_SCRIPTS = 'Scripts'


BOOK_TITLE_MIN_LENGTH = 1
BOOK_TITLE_MAX_LENGTH = 256