USER_COLLECTION_NAME = 'user'
USER_ID_ENTITY_NAME = 'ID'
USER_EMAIL_ENTITY_NAME = 'EMAIL'
USER_PHONE_ENTITY_NAME = 'PHONE'
USER_HASHED_PASSWORD_ENTITY_NAME = 'HASHED_PASSWORD'
USER_SALT_ENTITY_NAME = 'SALT'
USER_FIRST_NAME_ENTITY_NAME = 'FIRST_NAME'
USER_LAST_NAME_ENTITY_NAME = 'LAST_NAME'
USER_PROFILE_PICTURE_URL_ENTITY_NAME = 'PROFILE_PICTURE_URL'
USER_BIRTHDAY_ENTITY_NAME = 'BIRTHDAY'
USER_GENDER_ENTITY_NAME = 'GENDER'
USER_PASSWORD_RESET_CODE_ENTITY_NAME = 'PASSWORD_RESET_CODE'


USER_PASSWORD_MIN_LENGTH = 8
USER_PASSWORD_MAX_LENGTH = 256

BOOK_TITLE_MIN_LENGTH = 1
BOOK_TITLE_MAX_LENGTH = 128

USER_EMAIL_MAX_LENGTH = 256
