SECRET_KEY_LENGTH = 32
SERVER_EMAIL = 'smtp.gmail.com'
SERVER_EMAIL_PORT = 465
SERVER_EMAIL_USERNAME = ''  # TODO: add username
SERVER_EMAIL_PASSWORD = ''  # TODO: add password


JWT_ACCESS_TOKEN_LIFETIME_IN_MINUTES = 0.1
JWT_REFRESH_TOKEN_LIFETIME_IN_MINUTES = 60 * 24
