import os


SECRET_KEY_LENGTH = 32
SERVER_EMAIL = 'smtp.gmail.com'
SERVER_EMAIL_PORT = 465
SERVER_EMAIL_USERNAME = ''  # TODO: add username
SERVER_EMAIL_PASSWORD = ''  # TODO: add password


JWT_ACCESS_TOKEN_LIFETIME_IN_MINUTES = int(os.environ.get('JWT_ACCESS_TOKEN_LIFETIME_IN_MINUTES')) \
    if 'JWT_ACCESS_TOKEN_LIFETIME_IN_MINUTES' in os.environ else 0.05
JWT_REFRESH_TOKEN_LIFETIME_IN_MINUTES = int(os.environ.get('JWT_REFRESH_TOKEN_LIFETIME_IN_MINUTES')) \
    if 'JWT_REFRESH_TOKEN_LIFETIME_IN_MINUTES' in os.environ else 60 * 24
