USER_COLLECTION_NAME = 'user'
USER_ID_ENTITY_NAME = 'ID'
USER_EMAIL_ENTITY_NAME = 'EMAIL'
USER_PHONE_ENTITY_NAME = 'PHONE'
USER_PASSWORD_ENTITY_NAME = 'PASSWORD'
USER_FIRST_NAME_ENTITY_NAME = 'FIRST_NAME'
USER_LAST_NAME_ENTITY_NAME = 'LAST_NAME'
USER_PROFILE_PICTURE_URL_ENTITY_NAME = 'PROFILE_PICTURE_URL'


USER_PASSWORD_MIN_LENGTH = 8
USER_PASSWORD_MAX_LENGTH = 256

USER_NAME_MIN_LENGTH = 1
USER_NAME_MAX_LENGTH = 128

USER_EMAIL_MAX_LENGTH = 256
