ACCESS_TOKEN_HEADER_NAME = 'access_token'
REFRESH_TOKEN_HEADER_NAME = 'refresh_token'
MESSAGE_HEADER_NAME = 'message'
JSON_WEB_TOKEN_HEADER_NAME = 'Authorization'

USER_FIRST_NAME_HEADER_NAME = 'first_name'
USER_LAST_NAME_HEADER_NAME = 'last_name'
USER_email_HEADER_NAME = 'email'
USER_PROFILE_PICTURE_URL_HEADER_NAME = 'profile_image_url'
