LOGIN_ABS_ENDPOINT_NAME = '/login'
LOGIN_BY_TOKEN_ABS_ENDPOINT_NAME = '/login-token'

LOGIN_EMAIL_KEY_NAME = 'email'
LOGIN_PASSWORD_KEY_NAME = 'password'

ACCESS_TOKEN_LIFETIME = 60 * 24
REFRESH_TOKEN_LIFETIME = ACCESS_TOKEN_LIFETIME * 10

