LOGIN_ABS_ENDPOINT_NAME = '/login'
LOGIN_BY_TOKEN_ABS_ENDPOINT_NAME = '/login-token'

RES_ACCESS_TOKEN_KEY_NAME = 'access_token'
RES_REFRESH_TOKEN_NAME = 'refresh_token'
RES_USER_FIRST_NAME_KEY_NAME = 'first_name'
RES_USER_LAST_NAME_KEY_NAME = 'last_name'
RES_USER_EMAIL_KEY_NAME = 'email'
RES_USER_PROFILE_PICTURE_URL_KEY_NAME = 'profile_image_url'


