REGISTER_ABS_ENDPOINT_NAME = '/register'

REQ_USER_FIRST_NAME_KEY_NAME = 'first_name'
REQ_USER_LAST_NAME_KEY_NAME = 'last_name'
REQ_USER_PHONE_KEY_NAME = 'phone'
REQ_USER_PROFILE_PICTURE_DATA_KEY_NAME = 'profile_image_url'
REQ_USER_BIRTHDAY_KEY_NAME = 'birthday'
REQ_USER_GENDER_KEY_NAME = 'gender'
REQ_USER_BIRTHDAY_FORMAT = '%Y-%m-%d'  # e.g('1999-7-24')
