USER_ABS_ENDPOINT_NAME = '/user'


REQ_USER_ID_KEY_NAME = 'id'


RES_USER_ID_KEY_NAME = 'id'
RES_USER_EMAIL_KEY_NAME = 'email'
RES_USER_FIRST_NAME_KEY_NAME = 'first_name'
RES_USER_LAST_NAME_KEY_NAME = 'last_name'
RES_USER_PROFILE_PICTURE_URL_KEY_NAME = 'profile_image_url'
RES_USER_GENDER_KEY_NAME = 'gender'
RES_USER_BIRTHDAY_KEY_NAME = 'birthday'
RES_USER_PHONE_KEY_NAME = 'phone'
