"""''''''''''''''''''''''''''''''''''''''''values''''''''''''''''''''''''''''''''''"""
SECRET_VALUE = 'ASCX1234asides6SAD'
'''''''''''''''''''''''''''''''''''''''''''keys'''''''''''''''''''''''''''''''''''''''''''
TOKENS_KEY = 'tokens'
SENTENCES_KEY = 'data'
EMOTION_KEY = 'emotions'
SECRET_KEY = 'SECRET_KEY'
API_KEY = 'api'
'''''''''''''''''''''''''''''''''''''''''''Server keys'''''''''''''''''''''''''''''''''''''
EMOTION_DETECTION_SERVER = '/emotion-detection'
API_SERVER = '/api'
