RES_MESSAGE_KEY_NAME = 'message'


REQ_USER_EMAIL_KEY_NAME = 'email'
REQ_USER_PASSWORD_KEY_NAME = 'password'
REQ_USER_FIRST_NAME_KEY_NAME = 'first_name'
REQ_USER_LAST_NAME_KEY_NAME = 'last_name'
REQ_USER_PHONE_KEY_NAME = 'phone'
REQ_USER_PROFILE_PICTURE_DATA_KEY_NAME = 'profile_image_data'
REQ_USER_BIRTHDAY_KEY_NAME = 'birthday'
REQ_USER_GENDER_KEY_NAME = 'gender'
REQ_USER_BIRTHDAY_FORMAT = '%Y-%m-%d'  # e.g('1999-7-24')
REQ_GOOGLE_TOKEN_KEY_NAME = 'googleTokens'

REQ_JSON_WEB_TOKEN_HEADER_NAME = 'Authorization'
