LOGIN_ABS_ENDPOINT_NAME = '/login'
REFRESH_TOKEN_ABS_ENDPOINT_NAME = '/refresh-token'
FORGET_PASSWORD_ABS_ENDPOINT_NAME = '/forget-password'

RES_ACCESS_TOKEN_KEY_NAME = 'access_token'
RES_REFRESH_TOKEN_KEY_NAME = 'refresh_token'

REQ_USER_PASSWORD_RESET_CODE_KEY_NAME = 'password_reset_code'
